import type { VeneerLocale } from '@/lib/veneerI18n';

type HollywoodCopy = {
  title: string; description: string; eyebrow: string; heading: string; accent: string; lead: string;
  cta: string; secondaryCta: string; reassurance: string; facts: string[];
  imageAlt: string; imageTitle: string; imageNote: string;
  offerEyebrow: string; offerTitle: string; offerIntro: string; directTitle: string; indirectTitle: string;
  directText: string; indirectText: string; directFeatures: string[]; indirectFeatures: string[];
  offerCta: string; details: string; costNote: string;
  processEyebrow: string; processTitle: string; steps: { title: string; text: string }[];
  bookingEyebrow: string; bookingTitle: string; bookingIntro: string; nextTitle: string; next: string[];
  phoneLabel: string; directions: string; faqTitle: string; faqs: { question: string; answer: string }[];
};

export const hollywoodContent: Record<VeneerLocale, HollywoodCopy> = {
  hu: {
    title: 'Hollywood smile Esztergom – mosolytervezés és időpontkérés',
    description: 'Hollywoodi mosoly a Crown Dentalnál, Esztergomban. Direkt kompozit és saját laborban készülő porcelán héjak, átlátható fogankénti árak. Kérjen konzultációt online!',
    eyebrow: 'Hollywood smile · Crown Dental · Esztergom',
    heading: 'Hollywood smile.', accent: 'Önre tervezve.',
    lead: 'Természetesebb forma vagy ragyogóbb összhatás? Tervezzük meg együtt az Ön hollywoodi mosolyát – direkt kompozit vagy saját laborunkban készülő porcelán héjakkal.',
    cta: 'Mosolytervezési konzultációt kérek', secondaryCta: 'Megnézem a lehetőségeket',
    reassurance: 'Az időpontkérést követően kollégánk egyezteti Önnel a részleteket.',
    facts: ['Személyre szabott mosolyterv', 'Porcelán héjak saját laborból', 'Előre egyeztetett költségek'],
    imageAlt: 'Hollywood smile – mosoly a kezelés előtt és után, Crown Dental Esztergom',
    imageTitle: 'Előtte és utána', imageNote: 'A képen egy kezelési eredmény látható. Az elérhető változás egyénenként eltér.',
    offerEyebrow: 'Két lehetőség. Egy személyes döntés.', offerTitle: 'Melyik héj illik az Ön mosolyához?',
    offerIntro: 'Nem kell előre eldöntenie. Ismerje meg a két kezelést, a konzultáción pedig a fogai állapota és az elképzelései alapján választunk.',
    directTitle: 'Direkt kompozit héj', indirectTitle: 'Indirekt porcelán héj',
    directText: 'A fogorvos a rendelőben, közvetlenül a fog felszínén alakítja ki a kívánt formát fogszínű kompozitból.',
    indirectText: 'Egyénre készülő prémium kerámia héj, amelyet saját fogtechnikai laborunkban készítünk el a megtervezett mosolyhoz.',
    directFeatures: ['Közvetlen kialakítás a rendelőben', 'Egyénre választott szín és forma', 'Külön kezelési terv és fogankénti ár'],
    indirectFeatures: ['Prémium porcelán / kerámia', 'Saját fogtechnikai labor', 'Személyre tervezett kidolgozás'],
    offerCta: 'Konzultációt kérek', details: 'A kezelés részletei',
    costNote: 'Az árak foganként, forintban értendők. A teljes költséget a kezelt fogak száma és az esetleges előzetes kezelések határozzák meg; ezek díját előre egyeztetjük.',
    processEyebrow: 'Az első lépéstől a kezelési tervig', processTitle: 'Így indul a mosolytervezés',
    steps: [
      { title: 'Kérjen konzultációt', text: 'Adja meg elérhetőségét az alábbi űrlapon. Kollégánk felveszi Önnel a kapcsolatot az időpont egyeztetéséhez.' },
      { title: 'Nézzük meg együtt', text: 'Személyes vizsgálaton átbeszéljük a kívánt színt, formát és összhatást, valamint a szóba jövő kezeléseket.' },
      { title: 'Döntsön a részletek ismeretében', text: 'A kezelés megkezdése előtt egyeztetjük a javasolt megoldást, a fogak számát, a menetet és a várható költséget.' },
    ],
    bookingEyebrow: 'Az Ön mosolyával kezdjük', bookingTitle: 'Beszéljük át, mit szeretne elérni',
    bookingIntro: 'Kérjen időpontot Hollywood smile konzultációra itt, az oldalon. A megfelelő héjtípust a személyes vizsgálat után választjuk ki.',
    nextTitle: 'Mi történik az időpontkérés után?',
    next: ['Megkapjuk a kérését és felvesszük Önnel a kapcsolatot.', 'Egyeztetjük, majd visszaigazoljuk a rendelkezésre álló időpontot.', 'A konzultáción személyre szabott kezelési javaslatot beszélünk át.'],
    phoneLabel: 'Inkább telefonon egyeztetne?', directions: 'Megközelítés és elérhetőségek', faqTitle: 'Kérdések a hollywoodi mosolyról',
    faqs: [
      { question: 'Mi az a Hollywood smile, vagy hollywoodi mosoly?', answer: 'A Hollywood smile – amelyet „hollywoody mosoly” néven is keresnek – a személyre tervezett, harmonikus mosoly megnevezése. Nem egyetlen anyag vagy kötelező csomag: a kívánt megjelenéshez direkt kompozit vagy indirekt porcelán héj is szóba kerülhet.' },
      { question: 'El kell döntenem előre, melyik héjat szeretném?', answer: 'Nem. Az időpontkérésnél választhat Hollywood smile konzultációt. A fogorvos a fogai, az ínye és a harapása vizsgálata után, az elképzeléseivel együtt mérlegeli a lehetőségeket.' },
      { question: 'Hány fogra van szükség, és mennyi lesz a teljes ár?', answer: 'Nincs mindenkire érvényes fogszám. A fogankénti árak az ajánlatoknál láthatók; az érintett fogak számát és az esetleges előzetes kezeléseket a konzultáción pontosítjuk, így kap személyes költségtervet.' },
      { question: 'Minden esetben a héj a megfelelő megoldás?', answer: 'Nem feltétlenül. A vizsgálaton más lehetőségekről, például fogfehérítésről vagy fogszabályozásról is beszélhetünk. A héjak karbantartást, később javítást vagy cserét igényelhetnek. A szükséges fogelőkészítést és annak következményeit a kezelés előtt egyeztetjük.' },
      { question: 'Az űrlap elküldésével már végleges az időpontom?', answer: 'Az űrlap időpontkérés. Kollégánk egyezteti Önnel a részleteket és külön visszaigazolja az időpontot; a kiválasztott kezelés alkalmasságát személyes vizsgálat dönti el.' },
    ],
  },
  en: {
    title: 'Hollywood smile in Esztergom – smile design and consultation',
    description: 'Plan your Hollywood smile at Crown Dental in Esztergom, Hungary. Composite and in-house porcelain veneers, clear per-tooth prices and online consultation requests.',
    eyebrow: 'Hollywood smile · Crown Dental · Esztergom',
    heading: 'Hollywood smile.', accent: 'Designed around you.',
    lead: 'A more natural shape or a brighter overall look? Let’s plan your Hollywood smile together, with direct composite veneers or porcelain veneers made in our own laboratory.',
    cta: 'Request a smile consultation', secondaryCta: 'Explore the options',
    reassurance: 'Our team will contact you to arrange the details after your request.',
    facts: ['An individual smile plan', 'Porcelain veneers from our own lab', 'Costs agreed before treatment'],
    imageAlt: 'Hollywood smile before and after treatment at Crown Dental in Esztergom',
    imageTitle: 'Before and after', imageNote: 'This photograph shows one treatment result. Individual outcomes vary.',
    offerEyebrow: 'Two options. One personal decision.', offerTitle: 'Which veneers suit your smile?',
    offerIntro: 'You do not need to decide in advance. Explore both treatments; at your consultation we will consider your teeth and your preferences together.',
    directTitle: 'Direct composite veneers', indirectTitle: 'Indirect porcelain veneers',
    directText: 'The dentist shapes tooth-coloured composite directly on the tooth surface in the clinic.',
    indirectText: 'Individually crafted premium ceramic veneers, made in our own dental laboratory for your planned smile.',
    directFeatures: ['Shaped directly in the clinic', 'Individually selected colour and shape', 'A personal treatment plan and per-tooth price'],
    indirectFeatures: ['Premium porcelain / ceramic', 'Our own dental laboratory', 'Individually planned detailing'],
    offerCta: 'Request a consultation', details: 'Explore this treatment',
    costNote: 'All prices are per tooth in Hungarian forints (HUF). The total depends on the number of teeth and any preliminary treatment, with costs agreed in advance.',
    processEyebrow: 'From first contact to your treatment plan', processTitle: 'Your smile design starts here',
    steps: [
      { title: 'Request a consultation', text: 'Leave your contact details in the form below. Our team will contact you to arrange an appointment.' },
      { title: 'Explore your options together', text: 'At an in-person examination, we discuss the colour, shape and overall look you would like, and the available treatments.' },
      { title: 'Decide with the details in hand', text: 'Before treatment starts, we agree on the proposed solution, number of teeth, treatment steps and expected cost.' },
    ],
    bookingEyebrow: 'Let’s start with your smile', bookingTitle: 'Tell us what you would like to achieve',
    bookingIntro: 'Request your Hollywood smile consultation right here. The appropriate veneer type is chosen after an in-person examination.',
    nextTitle: 'What happens after your request?',
    next: ['We receive your request and contact you.', 'We arrange and confirm an available appointment.', 'At your consultation, we discuss a treatment proposal tailored to you.'],
    phoneLabel: 'Prefer to call us?', directions: 'Directions and contact details', faqTitle: 'Your Hollywood smile questions',
    faqs: [
      { question: 'What is a Hollywood smile?', answer: 'Hollywood smile describes a harmonious smile designed around the individual. It is not one specific material or a fixed package: direct composite or indirect porcelain veneers may be considered, depending on the intended look.' },
      { question: 'Do I need to choose a veneer type before booking?', answer: 'No. You can select a Hollywood smile consultation when requesting an appointment. Your dentist will assess your teeth, gums and bite and discuss the options alongside your preferences.' },
      { question: 'How many teeth need treatment and what is the total price?', answer: 'There is no set number of teeth for everyone. Per-tooth prices are shown in the offers. We confirm the number of teeth and any preliminary treatment at your consultation to prepare an individual cost plan.' },
      { question: 'Are veneers always the right choice?', answer: 'Not necessarily. At your examination we can also discuss alternatives such as whitening or orthodontics. Veneers need maintenance and may later need repair or replacement. Any required tooth preparation and its implications are discussed before treatment.' },
      { question: 'Does submitting the form confirm my appointment?', answer: 'The form sends an appointment request. Our team will discuss the details and confirm your appointment separately. An in-person examination determines whether the treatment is suitable.' },
    ],
  },
  de: {
    title: 'Hollywood Smile in Esztergom – Smile Design und Beratung',
    description: 'Ihr Hollywood Smile bei Crown Dental in Esztergom, Ungarn. Komposit-Veneers und Keramik-Veneers aus eigenem Labor, transparente Preise pro Zahn und Online-Terminanfrage.',
    eyebrow: 'Hollywood Smile · Crown Dental · Esztergom',
    heading: 'Hollywood Smile.', accent: 'Individuell geplant.',
    lead: 'Eine natürlichere Form oder ein strahlenderes Gesamtbild? Gemeinsam planen wir Ihr Hollywood Smile – mit direkten Komposit-Veneers oder Keramik-Veneers aus unserem eigenen Labor.',
    cta: 'Smile-Design-Beratung anfragen', secondaryCta: 'Möglichkeiten ansehen',
    reassurance: 'Nach Ihrer Anfrage meldet sich unser Team, um die Einzelheiten mit Ihnen abzustimmen.',
    facts: ['Individuelle Planung Ihres Lächelns', 'Keramik-Veneers aus eigenem Labor', 'Vorab abgestimmte Kosten'],
    imageAlt: 'Hollywood Smile vor und nach der Behandlung bei Crown Dental in Esztergom',
    imageTitle: 'Vorher und nachher', imageNote: 'Das Foto zeigt ein Behandlungsergebnis. Individuelle Ergebnisse können abweichen.',
    offerEyebrow: 'Zwei Möglichkeiten. Ihre persönliche Entscheidung.', offerTitle: 'Welche Veneers passen zu Ihrem Lächeln?',
    offerIntro: 'Sie müssen sich nicht vorab entscheiden. Lernen Sie beide Behandlungen kennen. Bei der Beratung berücksichtigen wir Ihre Zahnsituation und Ihre Wünsche.',
    directTitle: 'Direkte Komposit-Veneers', indirectTitle: 'Indirekte Keramik-Veneers',
    directText: 'Der Zahnarzt formt zahnfarbenes Komposit direkt auf der Zahnoberfläche in der Praxis.',
    indirectText: 'Individuell gefertigte Veneers aus hochwertiger Keramik, die in unserem eigenen zahntechnischen Labor für Ihr geplantes Lächeln entstehen.',
    directFeatures: ['Direkte Modellierung in der Praxis', 'Individuell gewählte Farbe und Form', 'Persönlicher Behandlungsplan und Preis pro Zahn'],
    indirectFeatures: ['Hochwertige Keramik / Porzellan', 'Eigenes zahntechnisches Labor', 'Individuell geplante Ausarbeitung'],
    offerCta: 'Beratung anfragen', details: 'Mehr zur Behandlung',
    costNote: 'Alle Preise gelten pro Zahn in ungarischen Forint (HUF). Die Gesamtkosten richten sich nach der Zahnanzahl und möglichen Vorbehandlungen; die Kosten stimmen wir vorab ab.',
    processEyebrow: 'Vom ersten Kontakt zum Behandlungsplan', processTitle: 'So beginnt Ihr Smile Design',
    steps: [
      { title: 'Beratung anfragen', text: 'Tragen Sie Ihre Kontaktdaten in das Formular ein. Unser Team meldet sich zur Terminvereinbarung.' },
      { title: 'Möglichkeiten gemeinsam besprechen', text: 'Bei der persönlichen Untersuchung besprechen wir die gewünschte Farbe, Form und Gesamtwirkung sowie die möglichen Behandlungen.' },
      { title: 'Mit allen Informationen entscheiden', text: 'Vor Behandlungsbeginn stimmen wir die vorgeschlagene Lösung, die Zahnanzahl, den Ablauf und die voraussichtlichen Kosten ab.' },
    ],
    bookingEyebrow: 'Ihr Lächeln steht am Anfang', bookingTitle: 'Was möchten Sie an Ihrem Lächeln verändern?',
    bookingIntro: 'Fragen Sie Ihre Hollywood-Smile-Beratung direkt hier an. Die geeignete Veneer-Art wählen wir nach einer persönlichen Untersuchung aus.',
    nextTitle: 'Was passiert nach Ihrer Anfrage?',
    next: ['Wir erhalten Ihre Anfrage und kontaktieren Sie.', 'Wir stimmen einen verfügbaren Termin ab und bestätigen ihn.', 'Bei der Beratung besprechen wir einen individuellen Behandlungsvorschlag.'],
    phoneLabel: 'Sie möchten lieber anrufen?', directions: 'Anfahrt und Kontakt', faqTitle: 'Fragen zu Hollywood Smile',
    faqs: [
      { question: 'Was versteht man unter Hollywood Smile?', answer: 'Hollywood Smile bezeichnet ein individuell geplantes, harmonisches Lächeln. Es ist weder ein bestimmtes Material noch ein festes Paket. Je nach gewünschtem Ergebnis kommen direkte Komposit-Veneers oder indirekte Keramik-Veneers infrage.' },
      { question: 'Muss ich die Veneer-Art schon vor der Terminanfrage wählen?', answer: 'Nein. Sie können bei der Anfrage eine Hollywood-Smile-Beratung auswählen. Der Zahnarzt untersucht Zähne, Zahnfleisch und Biss und bespricht die Möglichkeiten unter Berücksichtigung Ihrer Wünsche.' },
      { question: 'Wie viele Zähne werden behandelt und was kostet es insgesamt?', answer: 'Es gibt keine einheitliche Zahnanzahl. Die Preise pro Zahn stehen bei den Angeboten. Bei der Beratung klären wir die Anzahl und mögliche Vorbehandlungen und erstellen einen individuellen Kostenplan.' },
      { question: 'Sind Veneers immer die richtige Lösung?', answer: 'Nicht unbedingt. Bei der Untersuchung können auch Alternativen wie Zahnaufhellung oder Kieferorthopädie besprochen werden. Veneers benötigen Pflege und später möglicherweise Reparaturen oder Ersatz. Eine notwendige Zahnpräparation und ihre Folgen werden vor der Behandlung erläutert.' },
      { question: 'Ist mein Termin mit dem Absenden des Formulars bestätigt?', answer: 'Das Formular dient der Terminanfrage. Unser Team bespricht die Einzelheiten mit Ihnen und bestätigt den Termin separat. Ob die Behandlung geeignet ist, wird bei einer persönlichen Untersuchung geklärt.' },
    ],
  },
  sk: {
    title: 'Hollywood smile v Ostrihome – návrh úsmevu a konzultácia',
    description: 'Naplánujte si hollywoodsky úsmev v Crown Dental v Ostrihome. Kompozitné fazety a keramické fazety z vlastného laboratória, ceny za zub a online žiadosť o konzultáciu.',
    eyebrow: 'Hollywood smile · Crown Dental · Ostrihom',
    heading: 'Hollywood smile.', accent: 'Navrhnutý pre vás.',
    lead: 'Prirodzenejší tvar alebo žiarivejší celkový vzhľad? Naplánujme váš hollywoodsky úsmev spoločne – s priamymi kompozitnými fazetami alebo keramickými fazetami z nášho vlastného laboratória.',
    cta: 'Chcem konzultáciu o úsmeve', secondaryCta: 'Pozrieť možnosti',
    reassurance: 'Po odoslaní žiadosti vás náš tím kontaktuje a dohodne podrobnosti.',
    facts: ['Individuálny návrh úsmevu', 'Keramické fazety z vlastného laboratória', 'Vopred dohodnuté náklady'],
    imageAlt: 'Hollywood smile pred ošetrením a po ňom v Crown Dental v Ostrihome',
    imageTitle: 'Pred ošetrením a po ňom', imageNote: 'Fotografia zobrazuje jeden výsledok ošetrenia. Výsledky sa u jednotlivých pacientov líšia.',
    offerEyebrow: 'Dve možnosti. Vaše osobné rozhodnutie.', offerTitle: 'Ktoré fazety sa hodia k vášmu úsmevu?',
    offerIntro: 'Nemusíte sa rozhodnúť vopred. Spoznajte obe ošetrenia; pri konzultácii zohľadníme stav vašich zubov aj vaše predstavy.',
    directTitle: 'Priame kompozitné fazety', indirectTitle: 'Nepriame keramické fazety',
    directText: 'Zubný lekár vytvaruje kompozit vo farbe zubov priamo na povrchu zuba v ambulancii.',
    indirectText: 'Individuálne zhotovené fazety z prémiovej keramiky, ktoré vyrábame vo vlastnom zubnom laboratóriu pre váš plánovaný úsmev.',
    directFeatures: ['Priame tvarovanie v ambulancii', 'Individuálne zvolená farba a tvar', 'Osobný plán ošetrenia a cena za zub'],
    indirectFeatures: ['Prémiový porcelán / keramika', 'Vlastné zubné laboratórium', 'Individuálne navrhnuté spracovanie'],
    offerCta: 'Požiadať o konzultáciu', details: 'Podrobnosti o ošetrení',
    costNote: 'Všetky ceny sú za jeden zub v maďarských forintoch (HUF). Celková suma závisí od počtu zubov a prípadných predchádzajúcich ošetrení; náklady dohodneme vopred.',
    processEyebrow: 'Od prvého kontaktu k plánu ošetrenia', processTitle: 'Takto začína návrh vášho úsmevu',
    steps: [
      { title: 'Požiadajte o konzultáciu', text: 'Vyplňte kontaktné údaje vo formulári nižšie. Náš tím vás kontaktuje a dohodne termín.' },
      { title: 'Spoločne prejdeme možnosti', text: 'Pri osobnom vyšetrení preberieme požadovanú farbu, tvar a celkový vzhľad aj dostupné možnosti ošetrenia.' },
      { title: 'Rozhodnite sa so všetkými informáciami', text: 'Pred začatím ošetrenia dohodneme navrhované riešenie, počet zubov, postup a predpokladané náklady.' },
    ],
    bookingEyebrow: 'Začneme vaším úsmevom', bookingTitle: 'Povedzte nám, čo chcete dosiahnuť',
    bookingIntro: 'Požiadajte o konzultáciu Hollywood smile priamo tu. Vhodný typ faziet vyberieme po osobnom vyšetrení.',
    nextTitle: 'Čo sa stane po odoslaní žiadosti?',
    next: ['Dostaneme vašu žiadosť a kontaktujeme vás.', 'Dohodneme a potvrdíme dostupný termín.', 'Na konzultácii preberieme individuálny návrh ošetrenia.'],
    phoneLabel: 'Radšej nám zavoláte?', directions: 'Ako sa k nám dostať a kontakt', faqTitle: 'Otázky o hollywoodskom úsmeve',
    faqs: [
      { question: 'Čo znamená Hollywood smile?', answer: 'Hollywood smile označuje harmonický úsmev navrhnutý pre konkrétneho človeka. Nejde o jeden materiál ani pevne určený balík. Podľa požadovaného vzhľadu možno zvážiť priame kompozitné alebo nepriame keramické fazety.' },
      { question: 'Musím si vybrať typ faziet pred objednaním?', answer: 'Nie. Pri žiadosti o termín môžete vybrať konzultáciu Hollywood smile. Zubný lekár vyšetrí vaše zuby, ďasná a zhryz a preberie možnosti s ohľadom na vaše predstavy.' },
      { question: 'Koľko zubov treba ošetriť a aká bude celková cena?', answer: 'Neexistuje jednotný počet zubov pre každého. Ceny za zub nájdete pri ponukách. Počet zubov a prípadné predchádzajúce ošetrenia upresníme na konzultácii a pripravíme individuálny rozpočet.' },
      { question: 'Sú fazety vždy vhodným riešením?', answer: 'Nie vždy. Pri vyšetrení môžeme prebrať aj bielenie zubov alebo ortodontickú liečbu. Fazety vyžadujú starostlivosť a časom môžu potrebovať opravu či výmenu. Potrebnú prípravu zubov a jej dôsledky vysvetlíme pred ošetrením.' },
      { question: 'Je môj termín potvrdený odoslaním formulára?', answer: 'Formulár slúži na žiadosť o termín. Náš tím s vami dohodne podrobnosti a termín samostatne potvrdí. Vhodnosť ošetrenia sa posudzuje pri osobnom vyšetrení.' },
    ],
  },
};
