export const hidfutasRules = [
  { id: 'szervezo', title: '1. A játék szervezője', paragraphs: [
    'A „Crown Dental × Hídfutás 2026” nyereményjáték szervezője és adatkezelője a Crown Dental Praxis és Labor Fogászati Kft. Székhely: 2500 Esztergom, Petőfi Sándor utca 11. Cégjegyzékszám: 11-09-026431. Adószám: 26537353-2-11. Kapcsolat: info@crowndental.hu; +36 30 589 2468. A játék oldala: https://www.crowndental.hu/hidfutas.'
  ] },
  { id: 'idoszak', title: '2. Időtartam és részvétel', paragraphs: [
    'A nevezés 2026. szeptember 26-án 9:00-kor kezdődik és ugyanazon a napon 13:00-kor zárul. Minden időpont magyarországi helyi idő szerint értendő (Europe/Budapest). A szerver által rögzített időpont számít; a határidő után új nevezés nem fogadható el.',
    'A játékban a Hídfutás 18. életévüket betöltött résztvevői vehetnek részt. A részvétel ingyenes, vásárláshoz, kezelés igénybevételéhez vagy hírlevél-feliratkozáshoz nem kötött. Egy természetes személy egy alkalommal nevezhet és pörgethet. A szervező munkavállalói és a lebonyolításban közreműködők nem vehetnek részt.',
    'A QR-kód az oldalra vezet. A nevezéshez a résztvevő valós teljes nevét, saját e-mail-címét és telefonszámát adja meg, elfogadja a játékszabályzatot, nyilatkozik nagykorúságáról és megismeri az adatkezelési tájékoztatót. A „Pörgetek és nevezek” gombbal elküldött, sikeresen rögzített jelentkezés az azonnali játékra és a főnyeremény sorsolására egyaránt érvényes.',
    'A hírlevél külön, alapállapotban üres jelölőnégyzettel választható. A feliratkozás elutasítása vagy későbbi visszavonása a nevezést, a nyereményt és a nyerési esélyeket nem érinti.'
  ] },
  { id: 'azonnali', title: '3. Azonnali nyeremények és esélyek', paragraphs: [
    'A nyereményt a szerver véletlenszerűen, a nevezés rögzítésekor határozza meg. A kerék az így elmentett eredményt jeleníti meg. A kerék négy egyenlő esélyű mezőt tartalmaz. A kimenetelek: 1 db fogfehérítő csík – 25%; 1 db fogfehérítő por – 25%; 1 db fogselyem – 25%; 1 db szónikus fogkefe – 25%. Minden érvényes nevező nyer egy azonnali ajándékot. Az arányok egy pörgetés valószínűségei, nem garantált összesített darabszámok. A 25%-os esélyek a 2026-09-26-v3 szabályzat szerint rögzített új nevezésekre vonatkoznak. A korábbi nevezések eredménye és a már elnyert ajándékok változatlanok.',
    'Az eredmény végleges; újratöltés vagy ugyanannak a kérésnek az ismételt elküldése nem biztosít újabb pörgetést. Új nevezés ugyanazzal az e-mail-címmel vagy telefonszámmal nem fogadható el. A több e-mail-címmel, más személy adataival vagy automatizált módon történő többszörös részvétel szabálytalan.',
    'Az azonnali nyeremény a Crown Dental Hídfutáson felállított sátránál, 2026. szeptember 26-án 13:00-ig vehető át, a képernyőn megjelenő egyedi kód bemutatásával. A kód egyszer váltható be; az átadást a szervező rögzíti. A kódot a résztvevő őrizze meg, és ne ossza meg másokkal. Az átadó a nevezési adatok egyeztetését kérheti. Az átvétel elmulasztása nem érinti a főnyereményre szóló nevezést.',
    'A termékek rendeltetésszerű használatáról a csomagolás és a rendelő munkatársai adnak tájékoztatást. Az átadásnál a termékre vonatkozó korlátozásokat és a szükséges szakmai tájékoztatást biztosítani kell. A nyeremény nem váltható pénzre.'
  ] },
  { id: 'fonyeremeny', title: '4. Főnyeremény és sorsolás', paragraphs: [
    'A főnyeremény 1 fő részére 1 alkalom rendelői fogfehérítés a Crown Dental esztergomi rendelőjében, előre egyeztetett időpontban. A nyeremény a fogfehérítést és az ahhoz szükséges alkalmassági ellenőrzést tartalmazza. Az utazás és az esetleg szükséges egyéb kezelések nem részei a nyereménynek; külön kezelésre a nyertes nem kötelezhető.',
    'A sorsolásra 2026. szeptember 28-án, hétfőn kerül sor. Az összes érvényes nevezés azonos eséllyel vesz részt, az azonnali pörgetés eredményétől és a hírlevél-hozzájárulástól függetlenül. A szervező a belépéssel védett felületen indítja a szerveroldali, véletlenszerű sorsolást. A rendszer egy nyertest választ, a sorsolás időpontját és a résztvevők számát rögzíti. Ugyanaz a sorsolás újranyomással nem ismételhető meg.',
    'A szervező szeptember 28-án a megadott e-mail-címen és telefonon keresi a nyertest, és a Crown Dental Facebook-oldalán (facebook.com/koronafogaszatesztergom) közzéteszi a nyertes nevezési azonosítóját. E-mail-cím, telefonszám, teljes név és egészségügyi információ nem kerül nyilvánosságra. A nyertes külön, önkéntes hozzájárulása nélkül fénykép nem publikálható.',
    'A nyertes az első értesítéstől számított 7 napon belül jelezheti a nyeremény elfogadását az info@crowndental.hu címen vagy telefonon. Az időpontot a rendelővel kell egyeztetni; a beváltás határideje 2026. december 31. A nyeremény nem ruházható át és nem váltható készpénzre. Ha a nyertes nem jogosult a részvételre, visszautasítja a nyereményt vagy nem jelentkezik határidőben, a nyereményt nem adjuk át; ennek tényét dokumentáljuk.',
    'A fogfehérítés elvégezhetőségéről a fogorvos előzetes vizsgálat alapján dönt. A nyeremény nem jelent ígéretet meghatározott színváltozásra, és nem írhat felül egészségügyi ellenjavallatot. Alkalmatlanság esetén fogfehérítést nem végzünk; a további lehetőségeket a rendelő személyesen egyezteti a nyertessel.'
  ] },
  { id: 'adatkezeles', title: '5. A nyereményjáték adatkezelési tájékoztatója', paragraphs: [
    'Az adatkezelő az 1. pontban megjelölt szervező. A játékhoz kezelt adatok: név, normalizált e-mail-cím és telefonszám, nevezési és egyedi technikai azonosító, a szabályzat verziója és elfogadásának időpontja, a nagykorúsági nyilatkozat, a hírlevél-hozzájárulás állapota, a pörgetés eredménye, a nyeremény átadásának állapota és időpontja, valamint a sorsolás és a nyertessel való kapcsolatfelvétel adatai. Egészségügyi adatot a nevezési űrlap nem kér.',
    'A nevezés, a nyeremény megállapítása és átadása, a sorsolás, valamint a nyertes e-mailes és telefonos értesítésének jogalapja a játékban való részvétel feltételeinek teljesítése (GDPR 6. cikk (1) b)). A kötelező adatok nélkül a nevezést és a nyertes elérését nem tudjuk biztosítani. A telefonos elérhetőséget a játék lebonyolítására használjuk, nem jelent telefonos reklámhoz adott hozzájárulást.',
    'A visszaélések megelőzéséhez szükséges korlátozott technikai naplózás és a többszörös nevezés kiszűrésének jogalapja a szervező jogos érdeke (GDPR 6. cikk (1) f)). A nyertes nevezési kódjának nyilvánosságra hozatala az átlátható eredményhirdetést szolgáló jogos érdeken alapul. Ezekkel az adatkezelésekkel szemben a résztvevő a saját helyzetével kapcsolatos okból tiltakozhat. A nyeremény kiválasztása automatizált, egyenlő esélyű véletlen folyamat; a rendszer nem értékeli a résztvevő személyes tulajdonságait és nem végez profilalkotást.',
    'A külön kért e-mailes hírlevél jogalapja az önkéntes hozzájárulás (GDPR 6. cikk (1) a)). Célja a Crown Dental híreinek és ajánlatainak elküldése. A feliratkozáshoz a nevet, e-mail-címet, a hozzájárulás időpontját és forrását rögzítjük; a telefonszámot a hírlevélszolgáltatónak nem továbbítjuk. A hozzájárulás bármely hírlevél leiratkozási linkjén vagy az info@crowndental.hu címen visszavonható. A visszavonás a korábbi adatkezelés jogszerűségét nem érinti.',
    'A nevezési adatokat a játék lezárásától számított legfeljebb 90 napig őrizzük. A nyertesnek a nyeremény biztosításához szükséges adatait a beváltás lezárásáig kezeljük; jogi igény vagy kötelező bizonylat esetén a szükséges adatokat az irányadó határidőig elkülönítve őrizzük. A hírlevél-adatokat a hozzájárulás visszavonásáig kezeljük; a tiltás és a hozzájárulás bizonyításához szükséges minimális adatokat a vonatkozó jogos érdek alapján külön kezeljük. A sorsolási eredményhez kapcsolódó Facebook-közlést legfeljebb 90 nap után eltávolítjuk.',
    'Technikai adatfeldolgozók: Vercel Inc. (weboldal és szerverfunkciók), Supabase (adatbázis; az alkalmazott projekt EU-régiója Írország), valamint Resend (e-mail-küldés és önkéntesen választott hírlevél). A szolgáltatókhoz csak a feladatukhoz szükséges adatok kerülnek. EGT-n kívüli hozzáférés vagy adattovábbítás esetén a szolgáltatóval kötött adatfeldolgozói megállapodás szerinti garanciák, különösen az általános szerződési feltételek (SCC) alkalmazandók; ezekről a szervező elérhetőségén kérhető tájékoztatás. A Facebook önálló adatkezelésére a Meta tájékoztatója irányadó.',
    'A böngésző helyi tárhelyén csak a játék folytatásához szükséges technikai kérésazonosítót, az eredményt és a nevezési kódot tároljuk; a kitöltött nevet, e-mail-címet és telefonszámot nem. A helyi eredmény a böngésző webhelyadatainak törlésével eltávolítható; ez a szerveren már rögzített nevezést nem törli.',
    'Az érintett hozzáférést, helyesbítést, törlést, korlátozást és – feltételeinek fennállása esetén – adathordozhatóságot kérhet; a jogos érdeken alapuló adatkezelés ellen tiltakozhat, a hozzájárulást visszavonhatja. Kérelmét az info@crowndental.hu címre küldheti. A szervező főszabály szerint egy hónapon belül válaszol. A nevezés törlése a sorsolás előtt a részvétel megszüntetésével járhat. Panasz a Nemzeti Adatvédelmi és Információszabadság Hatóságnál tehető (naih.hu), továbbá bírósági jogorvoslat kérhető. A fogászati ellátásra külön adatkezelési tájékoztató vonatkozik.'
  ] },
  { id: 'egyeb', title: '6. Panasz, technikai hibák és egyéb feltételek', paragraphs: [
    'A játékkal kapcsolatos kérdés vagy panasz az info@crowndental.hu címen jelezhető, lehetőség szerint a nevezési kód megadásával. A szervező a panaszt kivizsgálja; a résztvevő törvényes jogait a szabályzat nem korlátozza. Bizonyítható visszaélés vagy valótlan adatok esetén a szervező a nevezést kizárhatja, az ok dokumentálásával.',
    'Kapcsolati hiba esetén csak a szerveren rögzített nevezés érvényes. A képernyőn látható animáció vagy annak technikai megszakadása nem módosítja a már elmentett eredményt. Elveszett kód vagy hibás elérhetőség esetén a résztvevő a helyszíni munkatársaktól vagy a szervező elérhetőségén kérhet segítséget.',
    'A játékot a Meta/Facebook nem támogatja, nem szervezi és nem kezeli. A részvételhez Facebook-fiók, megosztás, kedvelés vagy ismerős megjelölése nem szükséges. A játékban megadott adatok a szervezőhöz kerülnek. A szervező a jelen szabályzatot a játék indulása előtt teszi hozzáférhetővé; a már megszerzett nyereményeket utólagos módosítás nem csökkentheti.'
  ] },
] as const;
