const sharedGermanCopy: Record<string, string> = {
  'A durable option for missing teeth using Alpha Bio and DIO systems, subject to written guarantee terms.': 'Eine dauerhafte Möglichkeit bei fehlenden Zähnen mit Alpha-Bio- und DIO-Systemen gemäß den schriftlichen Garantiebedingungen.',
  'Metal-free crowns and bridges made with support from our in-house dental laboratory.': 'Metallfreie Kronen und Brücken mit Unterstützung unseres eigenen Dentallabors.',
  'Professional whitening planned after an oral assessment and individual consultation.': 'Professionelle Zahnaufhellung nach Untersuchung und individueller Beratung.',
  'Individually planned dentures with in-house laboratory support and local adjustment options.': 'Individuell geplanter Zahnersatz mit Unterstützung des eigenen Labors und Anpassungsmöglichkeiten vor Ort.',
  'Treatment aimed at retaining the tooth, performed with local anaesthesia and an individual plan.': 'Eine auf den Zahnerhalt ausgerichtete Behandlung mit örtlicher Betäubung und individuellem Plan.',
  'Dental examination with clinically indicated imaging to assess possible sources of inflammation.': 'Zahnärztliche Untersuchung mit medizinisch notwendiger Bildgebung zur Abklärung möglicher Entzündungsquellen.',
  'In-house dental laboratory': 'Eigenes Dentallabor',
  'Since 1994': 'Seit 1994',
  'local experience': 'Erfahrung vor Ort',
  'A long-established clinic in Esztergom.': 'Eine langjährig etablierte Praxis in Esztergom.',
  'In-house lab': 'Eigenes Labor',
  'direct collaboration': 'direkte Zusammenarbeit',
  'Dentists and dental technicians work as one team.': 'Zahnärzte und Zahntechniker arbeiten als ein Team.',
  '4 languages': '4 Sprachen',
  'clear information': 'verständliche Informationen',
  'Communication in Hungarian, Slovak, English and German.': 'Kommunikation auf Ungarisch, Slowakisch, Englisch und Deutsch.',
  'In writing': 'Schriftlich',
  'treatment plan': 'Behandlungsplan',
  'A transparent, personalised proposal after examination.': 'Ein transparenter, individueller Vorschlag nach der Untersuchung.',
  'What matters': 'Worauf es ankommt',
  'Production and fitting coordinated with the treatment plan': 'Herstellung und Anprobe abgestimmt auf den Behandlungsplan',
  'Local repairs and adjustments where clinically applicable': 'Reparaturen und Anpassungen vor Ort, soweit medizinisch sinnvoll',
  'Repairs and adjustments where appropriate for the individual case': 'Reparaturen und Anpassungen, soweit im Einzelfall sinnvoll',
  'Direct communication between dentist and dental technician': 'Direkte Kommunikation zwischen Zahnarzt und Zahntechniker',
  'Dentists and dental technicians collaborate directly.': 'Zahnärzte und Zahntechniker arbeiten direkt zusammen.',
  'direct teamwork': 'direkte Teamarbeit',
  'Esztergom experience': 'Erfahrung aus Esztergom',
  'The Budapest launch is backed by the existing Esztergom team.': 'Hinter dem Start in Budapest steht das bestehende Team aus Esztergom.',
  'Coordinated work between dentist and dental technician.': 'Abgestimmte Arbeit von Zahnarzt und Zahntechniker.',
  'Coming soon': 'Demnächst',
  'Budapest clinic': 'Praxis in Budapest',
  'Booking is not open yet; the launch will be announced separately.': 'Die Terminbuchung ist noch nicht geöffnet; der Start wird gesondert angekündigt.',
  'Our dental laboratory is based at the Esztergom clinic and will support Budapest treatment planning through direct coordination. Timing and final cost will depend on the individual case; Budapest booking is not open yet.': 'Unser Dentallabor befindet sich in der Praxis in Esztergom und wird die Behandlungsplanung in Budapest durch direkte Abstimmung unterstützen. Zeitplan und endgültige Kosten hängen vom Einzelfall ab; die Terminbuchung in Budapest ist noch nicht geöffnet.',
  'Yes. Our dental laboratory operates in the same building as the Esztergom clinic, allowing the dentist and dental technician to coordinate production and adjustments directly. Timing and final cost depend on the individual treatment plan.': 'Ja. Unser Dentallabor befindet sich im selben Gebäude wie die Praxis in Esztergom. Dadurch können Zahnarzt und Zahntechniker Herstellung und Anpassungen direkt abstimmen. Zeitplan und endgültige Kosten richten sich nach dem individuellen Behandlungsplan.',
}

export function translateLocationGerman(value: string): string {
  return sharedGermanCopy[value] ?? value
}
