export const siteCopy = {
  hu: {
    eyebrow: 'Crown Dental · Esztergom · 1994 óta',
    title: 'Szakértelem, amelyre', highlight: 'mosolyt építhet.',
    intro: 'Fogászat és saját fogtechnikai labor egy helyen. Személyes figyelem, korszerű diagnosztika és átlátható kezelési terv.',
    book: 'Időpontot kérek', treatments: 'Kezelések és árak', details: 'A kezelésről',
    call: 'Telefonálok', skip: 'Ugrás a tartalomra', contact: 'Elérhetőségek',
    clinic: 'Esztergomi rendelőnk', address: 'Petőfi Sándor utca 11.',
    lab: 'Saját fogtechnikai labor', languages: 'Magyar · English · Deutsch · Slovenčina',
    bookingEyebrow: 'Az első lépés egy beszélgetés',
    bookingIntro: 'Adja meg elérhetőségét és válasszon kezelést. Munkatársunk felveszi Önnel a kapcsolatot az időpont egyeztetéséhez.',
    steps: ['Elérhetőségek', 'Kezelés és küldés'],
    nextTitle: 'Mi történik ezután?',
    next: ['Elküldi az időpontkérést.', 'Felvesszük Önnel a kapcsolatot.', 'Közösen egyeztetjük a megfelelő időpontot.'],
    note: 'Ez időpontkérés, nem azonnal visszaigazolt foglalás.',
    help: 'Inkább telefonon egyeztetne?', required: 'A csillaggal jelölt mezők kitöltése kötelező.',
    optional: 'További információ (nem kötelező)', privacy: 'Adatkezelési tájékoztató',
    location: 'Válasszon rendelőt', back: 'Vissza a kezelésekhez',
    quote: 'Megnyitom az árajánlat-elemzőt',
  },
  en: {
    eyebrow: 'Crown Dental · Esztergom · Since 1994',
    title: 'Expert care.', highlight: 'A smile you can trust.',
    intro: 'Dentistry and an in-house dental laboratory under one roof. Personal attention, modern diagnostics and a clear treatment plan.',
    book: 'Request an appointment', treatments: 'Treatments & prices', details: 'About the treatment',
    call: 'Call us', skip: 'Skip to content', contact: 'Contact options',
    clinic: 'Our Esztergom clinic', address: 'Petőfi Sándor utca 11.',
    lab: 'In-house dental laboratory', languages: 'English · Magyar · Deutsch · Slovenčina',
    bookingEyebrow: 'It starts with a conversation',
    bookingIntro: 'Leave your contact details and choose a treatment. Our team will contact you to arrange an appointment.',
    steps: ['Contact details', 'Treatment & send'],
    nextTitle: 'What happens next?',
    next: ['Send your appointment request.', 'Our team contacts you.', 'We agree on a suitable appointment together.'],
    note: 'This is a request, not an instantly confirmed appointment.',
    help: 'Prefer to arrange it by phone?', required: 'Fields marked with an asterisk are required.',
    optional: 'Additional information (optional)', privacy: 'Privacy notice',
    location: 'Choose a clinic', back: 'Back to treatments',
    quote: 'Open the quote analyser',
  },
  de: {
    eyebrow: 'Crown Dental · Esztergom · Seit 1994',
    title: 'Kompetenz für', highlight: 'Ihr Lächeln.',
    intro: 'Zahnmedizin und eigenes Dentallabor unter einem Dach. Persönliche Betreuung, moderne Diagnostik und ein transparenter Behandlungsplan.',
    book: 'Termin anfragen', treatments: 'Behandlungen & Preise', details: 'Zur Behandlung',
    call: 'Anrufen', skip: 'Zum Inhalt springen', contact: 'Kontaktmöglichkeiten',
    clinic: 'Unsere Praxis in Esztergom', address: 'Petőfi Sándor utca 11.',
    lab: 'Eigenes Dentallabor', languages: 'Deutsch · Magyar · English · Slovenčina',
    bookingEyebrow: 'Der erste Schritt ist ein Gespräch',
    bookingIntro: 'Geben Sie Ihre Kontaktdaten an und wählen Sie eine Behandlung. Unser Team meldet sich zur Terminvereinbarung bei Ihnen.',
    steps: ['Kontaktdaten', 'Behandlung & senden'],
    nextTitle: 'Wie geht es weiter?',
    next: ['Sie senden Ihre Terminanfrage.', 'Unser Team kontaktiert Sie.', 'Gemeinsam vereinbaren wir einen passenden Termin.'],
    note: 'Dies ist eine Anfrage, kein sofort bestätigter Termin.',
    help: 'Möchten Sie lieber anrufen?', required: 'Mit einem Sternchen markierte Felder sind Pflichtfelder.',
    optional: 'Weitere Angaben (optional)', privacy: 'Datenschutzhinweise',
    location: 'Praxis auswählen', back: 'Zurück zu den Behandlungen',
    quote: 'Angebotsanalyse öffnen',
  },
  sk: {
    eyebrow: 'Crown Dental · Ostrihom · Od roku 1994',
    title: 'Odborná starostlivosť', highlight: 'pre váš úsmev.',
    intro: 'Zubná ambulancia a vlastné zubné laboratórium na jednom mieste. Osobný prístup, moderná diagnostika a zrozumiteľný liečebný plán.',
    book: 'Požiadať o termín', treatments: 'Ošetrenia a ceny', details: 'O ošetrení',
    call: 'Zavolať', skip: 'Prejsť na obsah', contact: 'Možnosti kontaktu',
    clinic: 'Naša ambulancia v Ostrihome', address: 'Petőfi Sándor utca 11.',
    lab: 'Vlastné zubné laboratórium', languages: 'Slovenčina · Magyar · English · Deutsch',
    bookingEyebrow: 'Prvým krokom je rozhovor',
    bookingIntro: 'Zadajte kontaktné údaje a vyberte ošetrenie. Náš tím vás bude kontaktovať a dohodne s vami termín.',
    steps: ['Kontaktné údaje', 'Ošetrenie a odoslanie'],
    nextTitle: 'Čo bude nasledovať?',
    next: ['Odošlete žiadosť o termín.', 'Náš tím vás kontaktuje.', 'Spoločne dohodneme vhodný termín.'],
    note: 'Ide o žiadosť, nie o okamžite potvrdený termín.',
    help: 'Radšej by ste sa dohodli telefonicky?', required: 'Polia označené hviezdičkou sú povinné.',
    optional: 'Doplňujúce informácie (nepovinné)', privacy: 'Ochrana osobných údajov',
    location: 'Vyberte ambulanciu', back: 'Späť na ošetrenia',
    quote: 'Otvoriť analýzu cenovej ponuky',
  },
} as const;

export function getSiteCopy(locale: string) {
  return siteCopy[locale === 'en' || locale === 'de' || locale === 'sk' ? locale : 'hu'];
}
